// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchRenameSummary } from "./BatchRenameSummary";
import type { FileRenameResult } from "./FileRenameResult";

/**
 * Complete result of a batch rename operation
 */
export type BatchRenameResult = { success: boolean, results: Array<FileRenameResult>, summary: BatchRenameSummary, startedAt: string, completedAt: string, durationMs: bigint, };
