// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error category for grouping and UI display
 */
export type ErrorCategory = "filesystem" | "security" | "config" | "network" | "validation" | "internal";
