// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCategory } from "./ErrorCategory";

/**
 * Structured error response for frontend
 * Enables the frontend to distinguish error types and provide appropriate recovery suggestions
 */
export type ErrorResponse = { 
/**
 * Error code for programmatic handling (e.g., "SCAN_PATH_NOT_FOUND")
 */
code: string, 
/**
 * Human-readable error message
 */
message: string, 
/**
 * Error category for grouping
 */
category: ErrorCategory, 
/**
 * Whether the error is recoverable
 */
recoverable: boolean, 
/**
 * Optional suggestion for the user
 */
suggestion: string | null, 
/**
 * Optional additional details (serialized as JSON object)
 */
details: Record<string, unknown> | null, };
