// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for executing renames
 */
export type ExecuteRenameOptions = { 
/**
 * IDs of proposals to rename (if empty, renames all ready)
 */
proposalIds: Array<string> | null, };
