// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Action type for a file in the preview.
 */
export type FileActionType = "rename" | "move" | "no-change" | "conflict" | "error";
