// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileCategory } from "./FileCategory";
import type { MetadataCapability } from "./MetadataCapability";

/**
 * Information about a scanned file
 */
export type FileInfo = { 
/**
 * Full absolute path to the file
 */
path: string, 
/**
 * Filename without extension
 */
name: string, 
/**
 * File extension (without dot)
 */
extension: string, 
/**
 * Full filename with extension
 */
fullName: string, 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * File creation timestamp
 */
createdAt: string, 
/**
 * File modification timestamp
 */
modifiedAt: string, 
/**
 * Path relative to scan root
 */
relativePath: string, 
/**
 * File category based on extension
 */
category: FileCategory, 
/**
 * Whether metadata extraction is supported
 */
metadataSupported: boolean, 
/**
 * Level of metadata capability
 */
metadataCapability: MetadataCapability, };
