// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Record of a single file operation
 */
export type FileHistoryRecord = { originalPath: string, newPath: string | null, isMoveOperation: boolean, success: boolean, error: string | null, };
