// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File category based on extension
 */
export type FileCategory = "image" | "document" | "video" | "audio" | "archive" | "code" | "data" | "other";
