// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaseStyle } from "./CaseStyle";
import type { OrganizeOptions } from "./OrganizeOptions";
import type { ReorganizationMode } from "./ReorganizationMode";

/**
 * Options for generating a preview
 */
export type GeneratePreviewOptions = { 
/**
 * Custom date format (default: YYYY-MM-DD)
 */
dateFormat: string | null, 
/**
 * Folder structure pattern for organizing files (e.g., "{year}/{month}")
 * DEPRECATED: Use reorganization_mode and organize_options instead
 */
folderPattern: string | null, 
/**
 * Base directory for folder organization (destination root)
 * DEPRECATED: Use reorganization_mode and organize_options instead
 */
baseDirectory: string | null, 
/**
 * Reorganization mode: 'rename-only' or 'organize'
 * Default: 'rename-only' (safest - files stay in place)
 */
reorganizationMode: ReorganizationMode, 
/**
 * Options for organize mode (required when reorganization_mode is 'organize')
 */
organizeOptions: OrganizeOptions | null, 
/**
 * Case style for filename normalization
 */
caseStyle: CaseStyle, 
/**
 * Strip existing date/counter patterns from filename before applying template
 * This prevents duplicate dates when re-applying templates (e.g., "2024-01-15_2024-01-15_photo")
 * Default: false (for backward compatibility)
 */
stripExistingPatterns: boolean, };
