// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of an operation
 */
export type OperationSummary = { succeeded: number, skipped: number, failed: number, directoriesCreated: number | null, };
