// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileHistoryRecord } from "./FileHistoryRecord";
import type { OperationSummary } from "./OperationSummary";
import type { OperationType } from "./OperationType";

/**
 * A single operation history entry
 */
export type OperationHistoryEntry = { id: string, timestamp: string, operationType: OperationType, fileCount: number, summary: OperationSummary, durationMs: bigint, files: Array<FileHistoryRecord>, directoriesCreated: Array<string> | null, undone: boolean, };
