// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for the "organize" mode.
 */
export type OrganizeOptions = { 
/**
 * Base destination directory for organized files.
 */
destinationDirectory: string | null, 
/**
 * Folder pattern for organizing files (e.g., "{year}/{month}").
 */
folderPattern: string, 
/**
 * Whether to preserve the relative context from subfolders.
 */
preserveContext: boolean, 
/**
 * How many levels of parent folders to preserve when preserve_context is true.
 */
contextDepth: number, };
