// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issue found with a rename proposal
 */
export type RenameIssue = { 
/**
 * Issue code for programmatic handling
 */
code: string, 
/**
 * Human-readable message
 */
message: string, 
/**
 * Field or placeholder that caused the issue (optional)
 */
field: string | null, };
