// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileActionType } from "./FileActionType";
import type { FileConflict } from "./FileConflict";
import type { RenameIssue } from "./RenameIssue";
import type { RenameStatus } from "./RenameStatus";

/**
 * A single file rename proposal
 */
export type RenameProposal = { 
/**
 * Unique identifier for selection tracking
 */
id: string, 
/**
 * Full path to original file
 */
originalPath: string, 
/**
 * Original filename (with extension)
 */
originalName: string, 
/**
 * Proposed new filename (with extension)
 */
proposedName: string, 
/**
 * Full path with proposed name
 */
proposedPath: string, 
/**
 * Status of this proposal
 */
status: RenameStatus, 
/**
 * Issues found with this proposal
 */
issues: Array<RenameIssue>, 
/**
 * Metadata source badges (e.g., "EXIF", "PDF", "filename")
 */
metadataSources: Array<string> | null, 
/**
 * Whether this proposal involves moving to a different folder
 */
isFolderMove: boolean, 
/**
 * The destination folder path (if is_folder_move is true)
 */
destinationFolder: string | null, 
/**
 * Action type for this proposal (rename, move, no-change, conflict, error)
 */
actionType: FileActionType, 
/**
 * Conflict details if status is Conflict
 */
conflict: FileConflict | null, };
