// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of a single file rename
 */
export type RenameOutcome = "success" | "failed" | "skipped";
