// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SanitizeChange } from "./SanitizeChange";

/**
 * Result of sanitizing a filename
 */
export type SanitizeResult = { sanitized: string, original: string, changes: Array<SanitizeChange>, wasModified: boolean, };
