// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanPhase } from "./ScanPhase";

/**
 * Progress event payload for scan operations
 */
export type ScanProgress = { 
/**
 * Scan session ID
 */
sessionId: string, 
/**
 * Current file being processed
 */
currentFile: string, 
/**
 * Number of files discovered so far
 */
discovered: number, 
/**
 * Number of files processed (after filtering)
 */
processed: number, 
/**
 * Current phase of scanning
 */
phase: ScanPhase, 
/**
 * Whether scan is complete
 */
complete: boolean, 
/**
 * Error message if any
 */
error: string | null, };
