// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phases of scanning operation
 */
export type ScanPhase = "starting" | "discovering" | "processing" | "complete" | "cancelled";
