// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";
import type { SkippedFile } from "./SkippedFile";

/**
 * Result of a folder scan
 */
export type ScanResult = { 
/**
 * List of scanned files
 */
files: Array<FileInfo>, 
/**
 * Total number of files found
 */
totalCount: number, 
/**
 * Total size in bytes
 */
totalSize: bigint, 
/**
 * Files that were skipped during scan (UX-002)
 */
skipped: Array<SkippedFile>, 
/**
 * Number of files skipped
 */
skippedCount: number, 
/**
 * Scan session ID (for tracking/cancellation)
 */
sessionId: string | null, 
/**
 * Whether the scan was cancelled
 */
cancelled: boolean, };
