// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkipReason } from "./SkipReason";

/**
 * Information about a file that was skipped during scan
 */
export type SkippedFile = { 
/**
 * Path to the skipped file
 */
path: string, 
/**
 * Reason the file was skipped
 */
reason: SkipReason, 
/**
 * Optional error message
 */
error: string | null, };
