// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reason why a file was skipped during scan
 */
export type SkipReason = "metadataError" | "filteredByExtension" | "permissionDenied" | "other";
