// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of batch rename results
 */
export type BatchRenameSummary = { total: number, succeeded: number, failed: number, skipped: number, };
