// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Case normalization style for filenames
 */
export type CaseStyle = "none" | "lowercase" | "uppercase" | "capitalize" | "title-case" | "kebab-case" | "snake-case" | "camel-case" | "pascal-case";
