// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenameOutcome } from "./RenameOutcome";

/**
 * Result of renaming a single file
 */
export type FileRenameResult = { proposalId: string, originalPath: string, originalName: string, newPath: string | null, newName: string | null, outcome: RenameOutcome, error: string | null, };
