// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conflict information for a file.
 */
export type FileConflict = { 
/**
 * The type of conflict
 */
type: string, 
/**
 * Human-readable description
 */
message: string, 
/**
 * ID of the conflicting file (for duplicate-name conflicts)
 */
conflictingFileId: string | null, 
/**
 * Path of the existing file (for file-exists conflicts)
 */
existingFilePath: string | null, };
