// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationHistoryEntry } from "./OperationHistoryEntry";

/**
 * The history store containing all entries
 */
export type HistoryStore = { version: string, entries: Array<OperationHistoryEntry>, lastModified: string, };
