// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary statistics for a rename preview
 */
export type PreviewSummary = { total: number, ready: number, conflicts: number, missingData: number, noChange: number, invalidName: number, };
