// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of preview actions by type.
 */
export type PreviewActionSummary = { renameCount: number, moveCount: number, noChangeCount: number, conflictCount: number, errorCount: number, };
