// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewActionSummary } from "./PreviewActionSummary";
import type { PreviewSummary } from "./PreviewSummary";
import type { RenameProposal } from "./RenameProposal";
import type { ReorganizationMode } from "./ReorganizationMode";

/**
 * Complete rename preview result
 */
export type RenamePreview = { 
/**
 * All file proposals
 */
proposals: Array<RenameProposal>, 
/**
 * Summary statistics
 */
summary: PreviewSummary, 
/**
 * When the preview was generated
 */
generatedAt: string, 
/**
 * Template pattern used
 */
templateUsed: string, 
/**
 * Action summary by type (rename vs move vs no-change etc.)
 */
actionSummary: PreviewActionSummary, 
/**
 * The reorganization mode used for this preview
 */
reorganizationMode: ReorganizationMode, };
