// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reorganization mode determines how files are handled during rename operations.
 *
 * - 'rename-only': Files stay in their current locations, only names change (safest)
 * - 'organize': Files are moved to new locations based on folder patterns
 */
export type ReorganizationMode = "rename-only" | "organize";
