// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a sanitization change
 */
export type SanitizeChange = { type: string, original: string, replacement: string, message: string, };
