// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for folder scanning
 */
export type ScanOptions = { 
/**
 * Scan subdirectories recursively (default: false)
 */
recursive: boolean, 
/**
 * Filter by file extensions (without dot, e.g., ["jpg", "png"])
 */
extensions: Array<string> | null, };
